# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ouroboros_pb2 as ouroboros__pb2


class OuroborosStub(object):
  """Ouroboros communication service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SyncJob = channel.unary_unary(
        '/Grpc.Ouroboros.Ouroboros/SyncJob',
        request_serializer=ouroboros__pb2.Request.SerializeToString,
        response_deserializer=ouroboros__pb2.Response.FromString,
        )
    self.StreamJob = channel.stream_stream(
        '/Grpc.Ouroboros.Ouroboros/StreamJob',
        request_serializer=ouroboros__pb2.Request.SerializeToString,
        response_deserializer=ouroboros__pb2.Response.FromString,
        )


class OuroborosServicer(object):
  """Ouroboros communication service definition.
  """

  def SyncJob(self, request, context):
    """A simple RPC.

    Obtains the `Response` based on the job asked in the `Request`
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamJob(self, request_iterator, context):
    """We have a method called `StreamJob` which takes
    parameter called `Request` and returns the message `Response`

    The stream keyword is specified before both the request type and response
    type to make it as bidirectional streaming RPC method.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OuroborosServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SyncJob': grpc.unary_unary_rpc_method_handler(
          servicer.SyncJob,
          request_deserializer=ouroboros__pb2.Request.FromString,
          response_serializer=ouroboros__pb2.Response.SerializeToString,
      ),
      'StreamJob': grpc.stream_stream_rpc_method_handler(
          servicer.StreamJob,
          request_deserializer=ouroboros__pb2.Request.FromString,
          response_serializer=ouroboros__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Grpc.Ouroboros.Ouroboros', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
