<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ouroboros.proto

namespace Grpc\Ouroboros;

/**
 * Ouroboros communication service definition.
 *
 * Protobuf type <code>Grpc.Ouroboros.Ouroboros</code>
 */
interface OuroborosInterface
{
    /**
     * A simple RPC.
     * Obtains the `Response` based on the job asked in the `Request`
     *
     * Method <code>syncJob</code>
     *
     * @param \Grpc\Ouroboros\Request $request
     * @return \Grpc\Ouroboros\Response
     */
    public function syncJob(\Grpc\Ouroboros\Request $request);

    /**
     * The stream keyword is specified before both the request type and response
     * type to make it as bidirectional streaming RPC method.
     *
     * Method <code>streamJob</code>
     *
     * @param \Grpc\Ouroboros\Request $request
     * @return \Grpc\Ouroboros\Response
     */
    public function streamJob(\Grpc\Ouroboros\Request $request);

}

