<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ouroboros.proto

namespace Grpc\Ouroboros;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Grpc.Ouroboros.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string job = 1;</code>
     */
    private $job = '';
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    private $message = '';

    public function __construct() {
        \GPBMetadata\Protos\Ouroboros::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string job = 1;</code>
     * @return string
     */
    public function getJob()
    {
        return $this->job;
    }

    /**
     * Generated from protobuf field <code>string job = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJob($var)
    {
        GPBUtil::checkString($var, True);
        $this->job = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

