<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ouroboros.proto

namespace GPBMetadata\Protos;

class Ouroboros
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8f020a1670726f746f732f6f75726f626f726f732e70726f746f120e47" .
            "7270632e4f75726f626f726f7322270a0752657175657374120b0a036a6f" .
            "62180120012809120f0a076d657373616765180220012809221b0a085265" .
            "73706f6e7365120f0a076d6573736167651801200128093291010a094f75" .
            "726f626f726f73123e0a0753796e634a6f6212172e477270632e4f75726f" .
            "626f726f732e526571756573741a182e477270632e4f75726f626f726f73" .
            "2e526573706f6e7365220012440a0953747265616d4a6f6212172e477270" .
            "632e4f75726f626f726f732e526571756573741a182e477270632e4f7572" .
            "6f626f726f732e526573706f6e73652200280130014203d0020162067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

